# Generated by Django 3.2.4 on 2021-07-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('F', 'Футболка'), ('SC', 'Спортивний костюм'), ('K', 'Кофта'), ('Ш', 'Штани')], default='SC', max_length=2, verbose_name='Тип товару')),
                ('description', models.TextField(max_length=300, verbose_name='Опис товару')),
                ('sizes', models.CharField(max_length=300, verbose_name="Розміри( наприклад 'S-3XL')")),
                ('price', models.FloatField(verbose_name='Ціна')),
                ('discount', models.IntegerField(default=0, verbose_name='Знижка(якщо є)')),
            ],
            options={
                'verbose_name': 'Профайл',
                'verbose_name_plural': 'Профайлы',
            },
        ),
    ]
