# Generated by Django 3.2.4 on 2021-07-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Товари', 'verbose_name_plural': 'Товари'},
        ),
    ]
