# Generated by Django 3.2.4 on 2021-07-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_items_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='name',
            field=models.CharField(default='default', max_length=300, verbose_name='Назва товару'),
            preserve_default=False,
        ),
    ]
