# Generated by Django 3.2.4 on 2021-08-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210704_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Главная картинка товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Ціна зі знижкою'),
        ),
    ]
