# Generated by Django 3.2.4 on 2021-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210805_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='product_images', verbose_name='Главная картинка товара'),
        ),
    ]
